CREATE (c1:Country {countryId: '1', name: 'USA'})
CREATE (c2:Country {countryId: '2', name: 'UK'})
CREATE (c3:Country {countryId: '3', name: 'Spain'})
CREATE (c4:Country {countryId: '4', name: 'France'})
CREATE (c5:Country {countryId: '5', name: 'Germany'})
CREATE (c6:Country {countryId: '6', name: 'Italy'})
CREATE (c7:Country {countryId: '7', name: 'Japan'})
CREATE (c8:Country {countryId: '8', name: 'South Korea'})
CREATE (c9:Country {countryId: '9', name: 'China'})
CREATE (c10:Country {countryId: '10', name: 'India'})